services:
  mysql:
    build:
      context: docker/mysql
      dockerfile: Dockerfile
    container_name: blog-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dev
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
  nginx:
    build:
      context: docker/nginx
      dockerfile: Dockerfile
    container_name: blog-nginx
    volumes:
      - ./docker/nginx/nginx:/etc/nginx
      - ./public_docroot:/blog.itxryx.com/public_docroot
      - ./admin_docroot:/blog.itxryx.com/admin_docroot
    ports:
        - "8080:8080"
        - "8081:8081"
    depends_on:
      - php-fpm
  php-fpm:
    build:
      context: docker/php-fpm
      dockerfile: Dockerfile
    container_name: blog-php
    working_dir: "/blog.itxryx.com/public_docroot"
    environment:
      DB_MYSQL_DSN: "mysql:host=mysql;port=3306;dbname=dev;charset=utf8mb4"
    volumes:
      - ./:/blog.itxryx.com
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini
