services:
  nginx:
    build:
      context: docker/nginx
      dockerfile: Dockerfile
    container_name: blog-nginx
    volumes:
      - ./docker/nginx/nginx:/etc/nginx
      - ./public_docroot:/blog.itxryx.com/public_docroot
      - ./admin_docroot:/blog.itxryx.com/admin_docroot
    ports:
        - "8080:8080"
        - "8081:8081"
    depends_on:
      - php-fpm
  php-fpm:
    build:
      context: docker/php-fpm
      dockerfile: Dockerfile
    container_name: blog-php
    working_dir: "/blog.itxryx.com/public_docroot"
    volumes:
      - ./:/blog.itxryx.com
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini
